#pragma checksum "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\_Imports.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "a70bb0b5ac007216258989a6bc8bfcfd86f11cac15b6102f7c91c33c3f7269ef"
// <auto-generated/>
#pragma warning disable 1591
namespace Alife.Function.Vision
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (1,2)-(1,43) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,17) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\_Imports.razor"
using AntDesign

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class _Imports : object
    #nullable disable
    {
        #pragma warning disable 1998
        protected void Execute()
        {
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
