#pragma checksum "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "cfcfad423322cc4a21ea1cfa2f44a59cd307bd0cafb0375d733b101debe7f466"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,33) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Alife.Function.Vision

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (1,2)-(1,43) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,17) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
using AntDesign

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,23) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
using Alife.Framework

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class VisionServiceUI : 
#nullable restore
#line (4,11)-(4,59) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
ModuleUIBase<VisionService, VisionServiceConfig>

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "style", "background: #fafafa; padding: 24px; border-radius: 12px; border: 1px solid #f0f0f0;");
            __builder.OpenComponent<global::AntDesign.Flex>(2);
            __builder.AddComponentParameter(3, nameof(global::AntDesign.Flex.
#nullable restore
#line (7,11)-(7,20) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Direction

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.FlexDirection>(
#nullable restore
#line (7,22)-(7,44) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
FlexDirection.Vertical

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(4, nameof(global::AntDesign.Flex.
#nullable restore
#line (7,46)-(7,49) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Gap

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::AntDesign.FlexGap, global::System.String>>(
#nullable restore
#line (7,53)-(7,57) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
"24"

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(5, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.OpenComponent<global::AntDesign.Card>(6);
                __builder2.AddComponentParameter(7, nameof(global::AntDesign.Card.
#nullable restore
#line (8,15)-(8,19) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Size

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.CardSize>(
#nullable restore
#line (8,21)-(8,35) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
CardSize.Small

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(8, nameof(global::AntDesign.Card.
#nullable restore
#line (8,37)-(8,42) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Title

#line default
#line hidden
#nullable disable
                ), "视觉感知");
                __builder2.AddComponentParameter(9, nameof(global::AntDesign.Card.
#nullable restore
#line (8,50)-(8,55) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Style

#line default
#line hidden
#nullable disable
                ), "border-radius: 8px;");
                __builder2.AddAttribute(10, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    __builder3.OpenComponent<global::AntDesign.Flex>(11);
                    __builder3.AddComponentParameter(12, nameof(global::AntDesign.Flex.
#nullable restore
#line (9,19)-(9,28) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Direction

#line default
#line hidden
#nullable disable
                    ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.FlexDirection>(
#nullable restore
#line (9,30)-(9,52) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
FlexDirection.Vertical

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddComponentParameter(13, nameof(global::AntDesign.Flex.
#nullable restore
#line (9,54)-(9,59) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Align

#line default
#line hidden
#nullable disable
                    ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::AntDesign.FlexAlign, global::System.String>>(
#nullable restore
#line (9,62)-(9,78) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
FlexAlign.Center

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddComponentParameter(14, nameof(global::AntDesign.Flex.
#nullable restore
#line (9,80)-(9,85) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Style

#line default
#line hidden
#nullable disable
                    ), "padding: 12px 0;");
                    __builder3.AddAttribute(15, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder4) => {
                        __builder4.OpenElement(16, "div");
                        __builder4.AddAttribute(17, "style", "margin-bottom: 16px;");
                        __builder4.OpenComponent<global::AntDesign.Badge>(18);
                        __builder4.AddComponentParameter(19, nameof(global::AntDesign.Badge.
#nullable restore
#line (11,28)-(11,34) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Status

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.BadgeStatus?>(
#nullable restore
#line (11,36)-(11,55) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
BadgeStatus.Default

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(20, nameof(global::AntDesign.Badge.
#nullable restore
#line (11,57)-(11,61) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Text

#line default
#line hidden
#nullable disable
                        ), "已就绪");
                        __builder4.CloseComponent();
                        __builder4.CloseElement();
                    }
                    ));
                    __builder3.CloseComponent();
                }
                ));
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(21, "\r\n\r\n        ");
                __builder2.OpenComponent<global::AntDesign.Form<
#nullable restore
#line (16,23)-(16,42) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
VisionServiceConfig

#line default
#line hidden
#nullable disable
                >>(22);
                __builder2.AddComponentParameter(23, nameof(global::AntDesign.Form<VisionServiceConfig>.
#nullable restore
#line (16,44)-(16,49) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Model

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<VisionServiceConfig>(
#nullable restore
#line (16,52)-(16,65) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Configuration

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(24, nameof(global::AntDesign.Form<VisionServiceConfig>.
#nullable restore
#line (16,67)-(16,73) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Layout

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.FormLayout>(
#nullable restore
#line (16,76)-(16,95) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
FormLayout.Vertical

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(25, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment<VisionServiceConfig>)((context) => (__builder3) => {
                    __builder3.OpenComponent<global::AntDesign.FormItem>(26);
                    __builder3.AddComponentParameter(27, nameof(global::AntDesign.FormItem.
#nullable restore
#line (17,23)-(17,28) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Label

#line default
#line hidden
#nullable disable
                    ), "图片附加提示词");
                    __builder3.AddAttribute(28, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder4) => {
                        __builder4.OpenComponent<global::AntDesign.TextArea>(29);
                        __builder4.AddComponentParameter(30, nameof(global::AntDesign.TextArea.
#nullable restore
#line (18,69)-(18,73) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Rows

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.UInt32>(
#nullable restore
#line (18,75)-(18,76) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
3

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(31, nameof(global::AntDesign.TextArea.
#nullable restore
#line (18,33)-(18,38) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Value

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (18,41)-(18,67) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Configuration.AppendPrompt

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(32, nameof(global::AntDesign.TextArea.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.String>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.String>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.AppendPrompt = __value, Configuration.AppendPrompt))));
                        __builder4.AddComponentParameter(33, nameof(global::AntDesign.TextArea.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.String>>>(() => Configuration.AppendPrompt));
                        __builder4.CloseComponent();
                        __builder4.AddMarkupContent(34, "\r\n                ");
                        __builder4.OpenComponent<global::AntDesign.Text>(35);
                        __builder4.AddComponentParameter(36, nameof(global::AntDesign.Text.
#nullable restore
#line (19,23)-(19,27) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Type

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.TextElementType?>(
#nullable restore
#line (19,29)-(19,54) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
TextElementType.Secondary

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(37, nameof(global::AntDesign.Text.
#nullable restore
#line (19,56)-(19,61) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Vision\VisionServiceUI.razor"
Style

#line default
#line hidden
#nullable disable
                        ), "font-size: 11px;");
                        __builder4.AddAttribute(38, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder5) => {
                            __builder5.AddMarkupContent(39, "\r\n                    这段话会自动拼接在模型分析图片时的 prompt 后面，以规范模型的输出格式和倾向。\r\n                ");
                        }
                        ));
                        __builder4.CloseComponent();
                    }
                    ));
                    __builder3.CloseComponent();
                }
                ));
                __builder2.CloseComponent();
            }
            ));
            __builder.CloseComponent();
            __builder.CloseElement();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
