#pragma checksum "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "0e751e4ea0776f2c685127b2c9161cb0532f7329f5733ed752f0123d61a1cbf5"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,33) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
Alife.Function.Speech

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (2,2)-(2,17) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
using AntDesign

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,23) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
using Alife.Framework

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class SpeechServiceUI : 
#nullable restore
#line (4,11)-(4,38) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
ModuleUIBase<SpeechService>

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "style", "background: #fafafa; padding: 24px; border-radius: 12px; border: 1px solid #f0f0f0;");
            __builder.OpenComponent<global::AntDesign.Card>(2);
            __builder.AddComponentParameter(3, nameof(global::AntDesign.Card.
#nullable restore
#line (7,11)-(7,15) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
Size

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.CardSize>(
#nullable restore
#line (7,17)-(7,31) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
CardSize.Small

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(4, nameof(global::AntDesign.Card.
#nullable restore
#line (7,33)-(7,38) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
Title

#line default
#line hidden
#nullable disable
            ), "语音合成 (TTS)");
            __builder.AddComponentParameter(5, nameof(global::AntDesign.Card.
#nullable restore
#line (7,52)-(7,57) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
Style

#line default
#line hidden
#nullable disable
            ), "border-radius: 8px;");
            __builder.AddAttribute(6, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.OpenComponent<global::AntDesign.Flex>(7);
                __builder2.AddComponentParameter(8, nameof(global::AntDesign.Flex.
#nullable restore
#line (8,15)-(8,24) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
Direction

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.FlexDirection>(
#nullable restore
#line (8,26)-(8,48) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
FlexDirection.Vertical

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(9, nameof(global::AntDesign.Flex.
#nullable restore
#line (8,50)-(8,55) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
Align

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::AntDesign.FlexAlign, global::System.String>>(
#nullable restore
#line (8,58)-(8,74) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
FlexAlign.Center

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(10, nameof(global::AntDesign.Flex.
#nullable restore
#line (8,76)-(8,81) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
Style

#line default
#line hidden
#nullable disable
                ), "padding: 12px 0;");
                __builder2.AddAttribute(11, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    __builder3.OpenElement(12, "div");
                    __builder3.AddAttribute(13, "style", "margin-bottom: 16px;");
#nullable restore
#line (10,1)-(10,17) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
                

#line default
#line hidden
#nullable disable

#nullable restore
#line (10,18)-(12,1) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
if (Module?.IsSpeaking == true)
                {

#line default
#line hidden
#nullable disable

                    __builder3.OpenComponent<global::AntDesign.Badge>(14);
                    __builder3.AddComponentParameter(15, nameof(global::AntDesign.Badge.
#nullable restore
#line (12,28)-(12,34) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
Status

#line default
#line hidden
#nullable disable
                    ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.BadgeStatus?>(
#nullable restore
#line (12,36)-(12,58) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
BadgeStatus.Processing

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddComponentParameter(16, nameof(global::AntDesign.Badge.
#nullable restore
#line (12,60)-(12,65) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
Color

#line default
#line hidden
#nullable disable
                    ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::AntDesign.BadgeColor?, global::System.String>>(
#nullable restore
#line (12,69)-(12,76) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
"green"

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddComponentParameter(17, nameof(global::AntDesign.Badge.
#nullable restore
#line (12,79)-(12,83) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
Text

#line default
#line hidden
#nullable disable
                    ), "正在播放语音...");
                    __builder3.CloseComponent();
#nullable restore
#line (13,1)-(16,1) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
                }
                else
                {

#line default
#line hidden
#nullable disable

                    __builder3.OpenComponent<global::AntDesign.Badge>(18);
                    __builder3.AddComponentParameter(19, nameof(global::AntDesign.Badge.
#nullable restore
#line (16,28)-(16,34) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
Status

#line default
#line hidden
#nullable disable
                    ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.BadgeStatus?>(
#nullable restore
#line (16,36)-(16,55) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
BadgeStatus.Default

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddComponentParameter(20, nameof(global::AntDesign.Badge.
#nullable restore
#line (16,57)-(16,61) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
Text

#line default
#line hidden
#nullable disable
                    ), "待机");
                    __builder3.CloseComponent();
#nullable restore
#line (17,1)-(18,1) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Speech\SpeechServiceUI.razor"
                }

#line default
#line hidden
#nullable disable

                    __builder3.CloseElement();
                }
                ));
                __builder2.CloseComponent();
            }
            ));
            __builder.CloseComponent();
            __builder.CloseElement();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
