#pragma checksum "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "12c2b98dfdbdd53947b0e64effe8b170cd38b213df185f3a6d0f90422d3b4e38"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,33) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Alife.Function.Speech

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (2,2)-(2,17) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
using AntDesign

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,23) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
using Alife.Framework

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,36) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
using Microsoft.Extensions.Logging

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class AuditoryServiceUI : 
#nullable restore
#line (5,11)-(5,63) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
ModuleUIBase<AuditoryService, AuditoryServiceConfig>

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "style", "background: #fafafa; padding: 24px; border-radius: 12px; border: 1px solid #f0f0f0;");
            __builder.OpenComponent<global::AntDesign.Flex>(2);
            __builder.AddComponentParameter(3, nameof(global::AntDesign.Flex.
#nullable restore
#line (9,11)-(9,20) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Direction

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.FlexDirection>(
#nullable restore
#line (9,22)-(9,44) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
FlexDirection.Vertical

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(4, nameof(global::AntDesign.Flex.
#nullable restore
#line (9,46)-(9,49) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Gap

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::AntDesign.FlexGap, global::System.String>>(
#nullable restore
#line (9,53)-(9,57) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
"24"

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(5, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.OpenElement(6, "div");
                __builder2.OpenComponent<global::AntDesign.Title>(7);
                __builder2.AddComponentParameter(8, nameof(global::AntDesign.Title.
#nullable restore
#line (11,20)-(11,25) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Level

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Int32>(
#nullable restore
#line (11,27)-(11,28) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
4

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(9, nameof(global::AntDesign.Title.
#nullable restore
#line (11,30)-(11,35) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Style

#line default
#line hidden
#nullable disable
                ), "margin-bottom: 16px;");
                __builder2.AddAttribute(10, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    __builder3.AddMarkupContent(11, "语音识别配置");
                }
                ));
                __builder2.CloseComponent();
                __builder2.CloseElement();
                __builder2.AddMarkupContent(12, "\r\n\r\n        ");
                __builder2.OpenComponent<global::AntDesign.Flex>(13);
                __builder2.AddComponentParameter(14, nameof(global::AntDesign.Flex.
#nullable restore
#line (14,15)-(14,24) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Direction

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.FlexDirection>(
#nullable restore
#line (14,26)-(14,48) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
FlexDirection.Vertical

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(15, nameof(global::AntDesign.Flex.
#nullable restore
#line (14,50)-(14,53) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Gap

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::AntDesign.FlexGap, global::System.String>>(
#nullable restore
#line (14,57)-(14,61) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
"16"

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(16, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    __builder3.OpenComponent<global::AntDesign.Flex>(17);
                    __builder3.AddComponentParameter(18, nameof(global::AntDesign.Flex.
#nullable restore
#line (16,19)-(16,28) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Direction

#line default
#line hidden
#nullable disable
                    ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.FlexDirection>(
#nullable restore
#line (16,30)-(16,54) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
FlexDirection.Horizontal

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddComponentParameter(19, nameof(global::AntDesign.Flex.
#nullable restore
#line (16,56)-(16,61) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Align

#line default
#line hidden
#nullable disable
                    ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::AntDesign.FlexAlign, global::System.String>>(
#nullable restore
#line (16,64)-(16,80) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
FlexAlign.Center

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddComponentParameter(20, nameof(global::AntDesign.Flex.
#nullable restore
#line (16,82)-(16,85) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Gap

#line default
#line hidden
#nullable disable
                    ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::AntDesign.FlexGap, global::System.String>>(
#nullable restore
#line (16,89)-(16,92) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
"8"

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddAttribute(21, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder4) => {
#nullable restore
#line (17,1)-(17,17) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
                

#line default
#line hidden
#nullable disable

#nullable restore
#line (17,18)-(19,1) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
if (Module?.IsRunning == true)
                {

#line default
#line hidden
#nullable disable

                        __builder4.OpenComponent<global::AntDesign.Badge>(22);
                        __builder4.AddComponentParameter(23, nameof(global::AntDesign.Badge.
#nullable restore
#line (19,28)-(19,34) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Status

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.BadgeStatus?>(
#nullable restore
#line (19,36)-(19,58) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
BadgeStatus.Processing

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(24, nameof(global::AntDesign.Badge.
#nullable restore
#line (19,60)-(19,64) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Text

#line default
#line hidden
#nullable disable
                        ), "正在监听中...");
                        __builder4.CloseComponent();
#nullable restore
#line (20,1)-(23,1) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
                }
                else
                {

#line default
#line hidden
#nullable disable

                        __builder4.OpenComponent<global::AntDesign.Badge>(25);
                        __builder4.AddComponentParameter(26, nameof(global::AntDesign.Badge.
#nullable restore
#line (23,28)-(23,34) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Status

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.BadgeStatus?>(
#nullable restore
#line (23,36)-(23,55) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
BadgeStatus.Default

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(27, nameof(global::AntDesign.Badge.
#nullable restore
#line (23,57)-(23,61) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Text

#line default
#line hidden
#nullable disable
                        ), "未启用");
                        __builder4.CloseComponent();
#nullable restore
#line (24,1)-(25,1) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
                }

#line default
#line hidden
#nullable disable

                    }
                    ));
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(28, "\r\n\r\n            ");
                    __builder3.OpenComponent<global::AntDesign.Flex>(29);
                    __builder3.AddComponentParameter(30, nameof(global::AntDesign.Flex.
#nullable restore
#line (28,19)-(28,28) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Direction

#line default
#line hidden
#nullable disable
                    ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.FlexDirection>(
#nullable restore
#line (28,30)-(28,52) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
FlexDirection.Vertical

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddComponentParameter(31, nameof(global::AntDesign.Flex.
#nullable restore
#line (28,54)-(28,57) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Gap

#line default
#line hidden
#nullable disable
                    ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::AntDesign.FlexGap, global::System.String>>(
#nullable restore
#line (28,61)-(28,64) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
"4"

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddAttribute(32, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder4) => {
                        __builder4.OpenComponent<global::AntDesign.Text>(33);
                        __builder4.AddComponentParameter(34, nameof(global::AntDesign.Text.
#nullable restore
#line (29,23)-(29,29) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Strong

#line default
#line hidden
#nullable disable
                        ), true);
                        __builder4.AddAttribute(35, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder5) => {
                            __builder5.AddMarkupContent(36, "按键说话");
                        }
                        ));
                        __builder4.CloseComponent();
                        __builder4.AddMarkupContent(37, "\r\n                ");
                        __builder4.OpenComponent<global::AntDesign.Text>(38);
                        __builder4.AddComponentParameter(39, nameof(global::AntDesign.Text.
#nullable restore
#line (30,23)-(30,27) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Type

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.TextElementType?>(
#nullable restore
#line (30,29)-(30,54) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
TextElementType.Secondary

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(40, nameof(global::AntDesign.Text.
#nullable restore
#line (30,56)-(30,61) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Style

#line default
#line hidden
#nullable disable
                        ), "font-size: 12px;");
                        __builder4.AddAttribute(41, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder5) => {
                            __builder5.AddMarkupContent(42, "\r\n                    选择一个按键，按住时才会进行语音识别。留空则始终监听。\r\n                ");
                        }
                        ));
                        __builder4.CloseComponent();
                        __builder4.AddMarkupContent(43, "\r\n                ");
                        __builder4.OpenComponent<global::AntDesign.Flex>(44);
                        __builder4.AddComponentParameter(45, nameof(global::AntDesign.Flex.
#nullable restore
#line (33,23)-(33,32) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Direction

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.FlexDirection>(
#nullable restore
#line (33,34)-(33,58) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
FlexDirection.Horizontal

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(46, nameof(global::AntDesign.Flex.
#nullable restore
#line (33,60)-(33,65) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Align

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::AntDesign.FlexAlign, global::System.String>>(
#nullable restore
#line (33,68)-(33,84) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
FlexAlign.Center

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(47, nameof(global::AntDesign.Flex.
#nullable restore
#line (33,86)-(33,89) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Gap

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::AntDesign.FlexGap, global::System.String>>(
#nullable restore
#line (33,93)-(33,96) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
"8"

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddAttribute(48, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder5) => {
                            __builder5.OpenComponent<global::AntDesign.Select<
#nullable restore
#line (34,41)-(34,47) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
string

#line default
#line hidden
#nullable disable
                            , 
#nullable restore
#line (34,56)-(34,62) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
string

#line default
#line hidden
#nullable disable
                            >>(49);
                            __builder5.AddComponentParameter(50, nameof(global::AntDesign.Select<string, string>.
#nullable restore
#line (35,29)-(35,34) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Style

#line default
#line hidden
#nullable disable
                            ), "width: 200px;");
                            __builder5.AddComponentParameter(51, nameof(global::AntDesign.Select<string, string>.
#nullable restore
#line (37,29)-(37,40) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Placeholder

#line default
#line hidden
#nullable disable
                            ), "始终监听（不设置）");
                            __builder5.AddComponentParameter(52, nameof(global::AntDesign.Select<string, string>.
#nullable restore
#line (38,29)-(38,39) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
AllowClear

#line default
#line hidden
#nullable disable
                            ), true);
                            __builder5.AddComponentParameter(53, nameof(global::AntDesign.Select<string, string>.
#nullable restore
#line (36,35)-(36,40) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Value

#line default
#line hidden
#nullable disable
                            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<string>(
#nullable restore
#line (36,42)-(36,69) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Configuration.PushToTalkKey

#line default
#line hidden
#nullable disable
                            ));
                            __builder5.AddComponentParameter(54, nameof(global::AntDesign.Select<string, string>.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<string>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<string>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.PushToTalkKey = __value, Configuration.PushToTalkKey))));
                            __builder5.AddComponentParameter(55, nameof(global::AntDesign.Select<string, string>.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<string>>>(() => Configuration.PushToTalkKey));
                            __builder5.AddAttribute(56, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder6) => {
#nullable restore
#line (39,1)-(39,25) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
                        

#line default
#line hidden
#nullable disable

#nullable restore
#line (39,26)-(41,1) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
foreach (var key in pushToTalkKeys)
                        {

#line default
#line hidden
#nullable disable

                                global::__Blazor.Alife.Function.Speech.AuditoryServiceUI.TypeInference.CreateSelectOption_0(__builder6, 57, default(string)!, 58, 
#nullable restore
#line (41,51)-(41,54) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
key

#line default
#line hidden
#nullable disable
                                , 59, 
#nullable restore
#line (41,64)-(41,67) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
key

#line default
#line hidden
#nullable disable
                                );
#nullable restore
#line (42,1)-(43,1) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
                        }

#line default
#line hidden
#nullable disable

                            }
                            ));
                            __builder5.CloseComponent();
#nullable restore
#line (44,1)-(44,21) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
                    

#line default
#line hidden
#nullable disable

#nullable restore
#line (44,22)-(46,25) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
if (Module != null && Module.Configuration?.PushToTalkKey == Configuration.PushToTalkKey && Configuration.PushToTalkKey != null)
                    {
                        

#line default
#line hidden
#nullable disable

#nullable restore
#line (46,26)-(48,1) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
if (Module.IsListening)
                        {

#line default
#line hidden
#nullable disable

                            __builder5.OpenComponent<global::AntDesign.Badge>(60);
                            __builder5.AddComponentParameter(61, nameof(global::AntDesign.Badge.
#nullable restore
#line (48,36)-(48,42) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Status

#line default
#line hidden
#nullable disable
                            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.BadgeStatus?>(
#nullable restore
#line (48,44)-(48,66) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
BadgeStatus.Processing

#line default
#line hidden
#nullable disable
                            ));
                            __builder5.AddComponentParameter(62, nameof(global::AntDesign.Badge.
#nullable restore
#line (48,68)-(48,72) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Text

#line default
#line hidden
#nullable disable
                            ), "按键已按下");
                            __builder5.CloseComponent();
#nullable restore
#line (49,1)-(52,1) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
                        }
                        else
                        {

#line default
#line hidden
#nullable disable

                            __builder5.OpenComponent<global::AntDesign.Badge>(63);
                            __builder5.AddComponentParameter(64, nameof(global::AntDesign.Badge.
#nullable restore
#line (52,36)-(52,42) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Status

#line default
#line hidden
#nullable disable
                            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.BadgeStatus?>(
#nullable restore
#line (52,44)-(52,63) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
BadgeStatus.Default

#line default
#line hidden
#nullable disable
                            ));
                            __builder5.AddComponentParameter(65, nameof(global::AntDesign.Badge.
#nullable restore
#line (52,65)-(52,69) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Text

#line default
#line hidden
#nullable disable
                            ), "等待按键");
                            __builder5.CloseComponent();
#nullable restore
#line (53,1)-(53,26) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
                        }

#line default
#line hidden
#nullable disable

#nullable restore
#line (53,26)-(55,1) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"

                    }

#line default
#line hidden
#nullable disable

                        }
                        ));
                        __builder4.CloseComponent();
                    }
                    ));
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(66, "\r\n\r\n            ");
                    __builder3.OpenComponent<global::AntDesign.Flex>(67);
                    __builder3.AddComponentParameter(68, nameof(global::AntDesign.Flex.
#nullable restore
#line (59,19)-(59,28) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Direction

#line default
#line hidden
#nullable disable
                    ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.FlexDirection>(
#nullable restore
#line (59,30)-(59,52) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
FlexDirection.Vertical

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddComponentParameter(69, nameof(global::AntDesign.Flex.
#nullable restore
#line (59,54)-(59,57) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Gap

#line default
#line hidden
#nullable disable
                    ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::AntDesign.FlexGap, global::System.String>>(
#nullable restore
#line (59,61)-(59,64) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
"4"

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddAttribute(70, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder4) => {
                        __builder4.OpenComponent<global::AntDesign.Button>(71);
                        __builder4.AddComponentParameter(72, nameof(global::AntDesign.Button.
#nullable restore
#line (60,25)-(60,29) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Type

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.ButtonType?>(
#nullable restore
#line (60,32)-(60,50) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
ButtonType.Default

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(73, nameof(global::AntDesign.Button.
#nullable restore
#line (60,52)-(60,56) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Size

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.ButtonSize>(
#nullable restore
#line (60,59)-(60,75) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
ButtonSize.Small

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(74, nameof(global::AntDesign.Button.
#nullable restore
#line (60,77)-(60,84) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
OnClick

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (60,87)-(60,102) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
ResetRecognizer

#line default
#line hidden
#nullable disable
                        )));
                        __builder4.AddComponentParameter(75, nameof(global::AntDesign.Button.
#nullable restore
#line (61,25)-(61,32) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Loading

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (61,35)-(61,47) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
isRestarting

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddAttribute(76, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder5) => {
                            __builder5.AddMarkupContent(77, "重置录音机\r\n                ");
                        }
                        ));
                        __builder4.CloseComponent();
                        __builder4.AddMarkupContent(78, "\r\n                ");
                        __builder4.OpenComponent<global::AntDesign.Text>(79);
                        __builder4.AddComponentParameter(80, nameof(global::AntDesign.Text.
#nullable restore
#line (63,23)-(63,27) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Type

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.TextElementType?>(
#nullable restore
#line (63,29)-(63,54) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
TextElementType.Secondary

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(81, nameof(global::AntDesign.Text.
#nullable restore
#line (63,56)-(63,61) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Style

#line default
#line hidden
#nullable disable
                        ), "font-size: 11px;");
                        __builder4.AddAttribute(82, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder5) => {
                            __builder5.AddMarkupContent(83, "\r\n                    当无法进行语音识别时，可以尝试重置录音机。\r\n                ");
                        }
                        ));
                        __builder4.CloseComponent();
                    }
                    ));
                    __builder3.CloseComponent();
                }
                ));
                __builder2.CloseComponent();
            }
            ));
            __builder.CloseComponent();
            __builder.CloseElement();
        }
        #pragma warning restore 1998
#nullable restore
#line (71,8)-(108,1) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"

    bool isRestarting;
    readonly string[] pushToTalkKeys = Enum.GetNames<ConsoleKey>();

    protected override void OnInitialized()
    {
        base.OnInitialized();
        if (Module != null)
            Module.IsListeningChanged += OnIsListeningChanged;
    }

    void OnIsListeningChanged(bool isListening)
    {
        InvokeAsync(StateHasChanged);
    }

    async Task ResetRecognizer()
    {
        if (Module == null)
            return;

        isRestarting = true;
        try
        {
            Module.StopRecording();
            await Module.StartRecordingAsync();
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "重启录音机失败");
        }
        finally
        {
            isRestarting = false;
            await InvokeAsync(StateHasChanged);
        }
    }

#line default
#line hidden
#nullable disable

        [global::Microsoft.AspNetCore.Components.InjectAttribute] private 
#nullable restore
#line (6,9)-(6,35) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
ILogger<AuditoryServiceUI>

#line default
#line hidden
#nullable disable
         
#nullable restore
#line (6,36)-(6,42) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Logger

#line default
#line hidden
#nullable disable
         { get; set; }
         = default!;
    }
}
namespace __Blazor.Alife.Function.Speech.AuditoryServiceUI
{
    #line hidden
    internal static class TypeInference
    {
        public static void CreateSelectOption_0<TItemValue, TItem>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, TItem __syntheticArg0, int __seq0, TItemValue __arg0, int __seq1, global::System.String __arg1)
        {
        __builder.OpenComponent<global::AntDesign.SelectOption<TItemValue, TItem>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::AntDesign.SelectOption<TItemValue, TItem>.
#nullable restore
#line (41,43)-(41,48) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::AntDesign.SelectOption<TItemValue, TItem>.
#nullable restore
#line (41,56)-(41,61) "C:\Users\13309\Desktop\Alife\Sources\Alife.Function\Alife.Function.Auditory\AuditoryServiceUI.razor"
Label

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.CloseComponent();
        }
    }
}
#pragma warning restore 1591
